merge_queue:
  mode: serial
  max_parallel_checks: 1

queue_rules:
  - name: default
    batch_size: 1
    max_checks_retries: 0
    merge_method: squash

pull_request_rules:
  - name: queue ready main pull requests
    conditions:
      - base = main
      - -draft
    actions:
      queue:
        name: default
