export const UI_ICON_SOURCES = {
  account: { package: 'vsc', exportName: 'VscAccount' },
  'arrow-left': { package: 'vsc', exportName: 'VscArrowLeft' },
  'arrow-right': { package: 'vsc', exportName: 'VscArrowRight' },
  bell: { package: 'vsc', exportName: 'VscBell' },
  book: { package: 'vsc', exportName: 'VscBook' },
  briefcase: { package: 'vsc', exportName: 'VscBriefcase' },
  calendar: { package: 'vsc', exportName: 'VscCalendar' },
  check: { package: 'vsc', exportName: 'VscCheck' },
  'chevron-right': { package: 'vsc', exportName: 'VscChevronRight' },
  'circuit-board': { package: 'vsc', exportName: 'VscCircuitBoard' },
  close: { package: 'vsc', exportName: 'VscClose' },
  code: { package: 'vsc', exportName: 'VscCode' },
  'color-mode': { package: 'vsc', exportName: 'VscColorMode' },
  edit: { package: 'vsc', exportName: 'VscEdit' },
  error: { package: 'vsc', exportName: 'VscError' },
  files: { package: 'vsc', exportName: 'VscFiles' },
  'folder-opened': { package: 'vsc', exportName: 'VscFolderOpened' },
  gear: { package: 'vsc', exportName: 'VscGear' },
  github: { package: 'vsc', exportName: 'VscGithub' },
  'github-alt': { package: 'vsc', exportName: 'VscGithubAlt' },
  globe: { package: 'vsc', exportName: 'VscGlobe' },
  'go-to-file': { package: 'vsc', exportName: 'VscGoToFile' },
  home: { package: 'vsc', exportName: 'VscHome' },
  'link-external': { package: 'vsc', exportName: 'VscLinkExternal' },
  mail: { package: 'vsc', exportName: 'VscMail' },
  'navigate-next': { package: 'md', exportName: 'MdNavigateNext' },
  nextjs: { package: 'si', exportName: 'SiNextdotjs' },
  person: { package: 'vsc', exportName: 'VscPerson' },
  pulse: { package: 'vsc', exportName: 'VscPulse' },
  repo: { package: 'vsc', exportName: 'VscRepo' },
  'repo-forked': { package: 'vsc', exportName: 'VscRepoForked' },
  search: { package: 'vsc', exportName: 'VscSearch' },
  send: { package: 'vsc', exportName: 'VscSend' },
  server: { package: 'vsc', exportName: 'VscServer' },
  settings: { package: 'vsc', exportName: 'VscSettings' },
  shield: { package: 'vsc', exportName: 'VscShield' },
  'source-control': { package: 'vsc', exportName: 'VscSourceControl' },
  'star-empty': { package: 'vsc', exportName: 'VscStarEmpty' },
  'symbol-color': { package: 'vsc', exportName: 'VscSymbolColor' },
  tag: { package: 'vsc', exportName: 'VscTag' },
  terminal: { package: 'vsc', exportName: 'VscTerminal' },
  warning: { package: 'vsc', exportName: 'VscWarning' },
} as const;

export type UiIconName = keyof typeof UI_ICON_SOURCES;

export const UI_ICON_NAMES = Object.freeze(
  Object.keys(UI_ICON_SOURCES) as UiIconName[],
);
